#!/bin/bash

execute_config_script () {
  chmod +x $1
  . $1 $2
}

##########################################
echo "Setting Hostname"
hn=$(execute_config_script "/home/pi/setup/create_hostname")
hn=$(echo $hn)
echo $hn

sudo hostname -b $hn

##########################################
echo "Setting up Cron for restart"
rj=$(execute_config_script  "/home/pi/setup/set_up_restart")
echo "$rj"
##########################################
echo cleaning up
sudo rm /boot/firstboot

echo "restart required"
sudo reboot now