#!/bin/bash

. /home/pi/setup/setup.config
#write out current crontab
sudo crontab -l > tmpc
job="$(echo "$config_restart")"
job+=" /sbin/shutdown -r"
echo "$job" >> tmpc

#install new cron file
sudo crontab tmpc
rm tmpc
echo "$job"